// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/clouds/node/:node_name/containers/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "创建容器",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "获取所有容器列表",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/log": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "容器日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "容器名称",
                        "name": "containerName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "容器ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否监听日志",
                        "name": "isWatch",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "获取日志范围, all,1m,10m...",
                        "name": "mode",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/option": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "容器操作选项",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "获取指定容器",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/state/:container_id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "获取容器资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "容器ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/containers/state/:id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "容器"
                ],
                "summary": "容器终端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "容器ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "执行命令",
                        "name": "command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/images/delete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "镜像"
                ],
                "summary": "删除镜像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "镜像名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/images/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "镜像"
                ],
                "summary": "获取所有镜像",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/images/pull": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "镜像"
                ],
                "summary": "拉取镜像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "镜像名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/images/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "镜像"
                ],
                "summary": "搜索镜像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "镜像名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/networks/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络"
                ],
                "summary": "创建网络",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/networks/delete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络"
                ],
                "summary": "删除网络",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/networks/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络"
                ],
                "summary": "获取所有网络列表",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/networks/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络"
                ],
                "summary": "搜索网络",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/volumes/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "卷"
                ],
                "summary": "创建卷",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/volumes/delete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "卷"
                ],
                "summary": "删除卷",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/volumes/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "卷"
                ],
                "summary": "获取所有卷",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/:node_name/volumes/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "卷"
                ],
                "summary": "搜索卷",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"请求成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点"
                ],
                "summary": "创建 Docker 节点",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"创建失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/delete": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点"
                ],
                "summary": "删除 Docker 节点",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"删除失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clouds/node/update": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点"
                ],
                "summary": "更新 Docker 节点",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"更新失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
